export interface Scheme {
  id: string;
  name: string;
  category: string;
  central_or_state: "Central" | "State" | "Both";
  applicable_states: string[]; // ["All"] for Central
  description: string;
  benefits: string;
  required_documents: string[];
  application_link: string | null;
  offline_process: string | null;
  nearest_office: string | null;
  tags: string[];
  
  // Rule-based matching engine fields
  target_gender: "All" | "Female" | "Male" | "Other";
  target_occupations: string[]; // e.g. ["Farmer", "Student", "Daily Wage Labourer", "Unemployed", "All"]
  min_age: number | null;
  max_age: number | null;
  income_limit: number | null;
  is_student_only: boolean;
  is_farmer_only: boolean;
  is_pregnant_only: boolean;
  is_senior_only: boolean;
  is_daily_wage_only: boolean;
  is_bpl_only: boolean;
}

export const mockSchemes: Scheme[] = [
  // =====================
  // FARMERS
  // =====================
  {
    id: "pm-kisan",
    name: "PM-Kisan Samman Nidhi",
    category: "Farmers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Financial assistance for landholding farmer families across the country.",
    benefits: "₹6,000 per year transferred in three equal installments of ₹2,000 directly to bank accounts.",
    required_documents: ["Aadhaar Card", "Land holding documents", "Bank account details"],
    application_link: "https://pmkisan.gov.in/",
    offline_process: null,
    nearest_office: "Common Service Centre (CSC) or local Patwari office.",
    tags: ["farmer", "financial", "agriculture"],
    target_gender: "All",
    target_occupations: ["Farmer", "Agriculture"],
    min_age: 18,
    max_age: null,
    income_limit: null, // Specific exclusion criteria apply, but broadly for all landholding
    is_student_only: false,
    is_farmer_only: true,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "pm-fasal-bima-yojana",
    name: "PM Fasal Bima Yojana",
    category: "Farmers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Crop insurance scheme to provide financial support to farmers suffering crop loss/damage.",
    benefits: "Comprehensive insurance cover against failure of the crop helping in stabilising the income.",
    required_documents: ["Aadhaar Card", "Land Records", "Sowing Certificate", "Bank Passbook"],
    application_link: "https://pmfby.gov.in/",
    offline_process: null,
    nearest_office: "CSC or nearest Bank Branch.",
    tags: ["farmer", "insurance", "agriculture"],
    target_gender: "All",
    target_occupations: ["Farmer", "Agriculture"],
    min_age: 18,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: true,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "ysr-rythu-bharosa",
    name: "YSR Rythu Bharosa",
    category: "Farmers",
    central_or_state: "State",
    applicable_states: ["Andhra Pradesh"],
    description: "Financial assistance to farmers, including tenant farmers, in Andhra Pradesh.",
    benefits: "₹13,500 per year for five years (includes PM-Kisan benefit).",
    required_documents: ["Aadhaar Card", "Land records / Tenant proof", "Bank account passbook", "Resident proof of AP"],
    application_link: "https://ysrrythubharosa.ap.gov.in/",
    offline_process: null,
    nearest_office: "Rythu Bharosa Kendra (RBK)",
    tags: ["farmer", "andhra pradesh", "agriculture"],
    target_gender: "All",
    target_occupations: ["Farmer", "Agriculture"],
    min_age: 18,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: true,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "kisan-credit-card",
    name: "Kisan Credit Card (KCC)",
    category: "Farmers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Provides farmers with timely access to credit for agricultural and allied activities.",
    benefits: "Short-term credit limits for crop production, post-harvest expenses, and consumption needs.",
    required_documents: ["Aadhaar Card", "PAN Card", "Land Records", "Passport size photograph"],
    application_link: null,
    offline_process: "Visit your nearest Commercial Bank, Cooperative Bank, or Regional Rural Bank branch to apply via the KCC application form.",
    nearest_office: "Any Bank Branch",
    tags: ["farmer", "credit", "loan", "agriculture"],
    target_gender: "All",
    target_occupations: ["Farmer", "Agriculture"],
    min_age: 18,
    max_age: 75,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: true,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "soil-health-card",
    name: "Soil Health Card Scheme",
    category: "Farmers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Provides information to farmers on nutrient status of their soil.",
    benefits: "Improves crop yield by promoting balanced use of fertilizers.",
    required_documents: ["Aadhaar Card", "Land Details"],
    application_link: "https://soilhealth.dac.gov.in/",
    offline_process: null,
    nearest_office: "Department of Agriculture / Soil Testing Lab",
    tags: ["farmer", "soil", "agriculture"],
    target_gender: "All",
    target_occupations: ["Farmer", "Agriculture"],
    min_age: 18,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: true,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },

  // =====================
  // STUDENTS
  // =====================
  {
    id: "national-scholarship-portal",
    name: "National Scholarship Portal (NSP)",
    category: "Students",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "A one-stop platform for various scholarships offered by the Central Government.",
    benefits: "Financial assistance for education (varies by specific scheme).",
    required_documents: ["Aadhaar Card", "Income Certificate", "Caste Certificate (if applicable)", "Previous Year Marksheet", "Bank details"],
    application_link: "https://scholarships.gov.in/",
    offline_process: null,
    nearest_office: "Educational Institution / School",
    tags: ["student", "education", "scholarship", "financial"],
    target_gender: "All",
    target_occupations: ["Student"],
    min_age: null,
    max_age: 30,
    income_limit: 250000,
    is_student_only: true,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "pm-yasasvi",
    name: "PM-YASASVI Scholarship",
    category: "Students",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Scholarship scheme for OBC, EBC and DNT students.",
    benefits: "Pre-matric and Post-matric scholarships.",
    required_documents: ["Aadhaar Card", "Income Certificate (<2.5 Lakhs)", "Caste Certificate", "Marksheet"],
    application_link: "https://yet.nta.ac.in/",
    offline_process: null,
    nearest_office: "School / College",
    tags: ["student", "education", "scholarship", "obc"],
    target_gender: "All",
    target_occupations: ["Student"],
    min_age: null,
    max_age: null,
    income_limit: 250000,
    is_student_only: true,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "aicte-pragati",
    name: "AICTE Pragati Scholarship for Girls",
    category: "Students",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Scholarship for girl students pursuing technical education (Degree/Diploma).",
    benefits: "₹50,000 per annum for every year of study.",
    required_documents: ["Aadhaar Card", "Income Certificate (<8 Lakhs)", "10th/12th Marksheet", "Admission Letter"],
    application_link: "https://www.aicte-india.org/schemes/students-development-schemes/Pragati-Scholarship-Scheme",
    offline_process: null,
    nearest_office: "College / AICTE Office",
    tags: ["student", "education", "scholarship", "women", "technical"],
    target_gender: "Female",
    target_occupations: ["Student"],
    min_age: 16,
    max_age: null,
    income_limit: 800000,
    is_student_only: true,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },

  // =====================
  // DAILY WAGE & UNORGANIZED WORKERS
  // =====================
  {
    id: "e-shram",
    name: "e-Shram Card",
    category: "Labourers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "National Database of Unorganized Workers (NDUW) for social security.",
    benefits: "₹2 Lakh Accidental Insurance cover under PMSBY for a year.",
    required_documents: ["Aadhaar Card", "Bank Account Details", "Mobile Number linked to Aadhaar"],
    application_link: "https://eshram.gov.in/",
    offline_process: null,
    nearest_office: "CSC Centre",
    tags: ["labour", "unorganized worker", "insurance", "registration"],
    target_gender: "All",
    target_occupations: ["Daily Wage Labourer", "Unorganized Worker", "Labourer"],
    min_age: 16,
    max_age: 59,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: true,
    is_bpl_only: false
  },
  {
    id: "pm-shram-yogi-maandhan",
    name: "PM Shram Yogi Maandhan (PM-SYM)",
    category: "Labourers",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "A voluntary and contributory pension scheme for unorganized workers.",
    benefits: "Assured minimum monthly pension of ₹3,000 after attaining the age of 60 years.",
    required_documents: ["Aadhaar Card", "Savings Bank Account / Jan Dhan Account Details"],
    application_link: "https://maandhan.in/shramyogi",
    offline_process: null,
    nearest_office: "CSC Centre",
    tags: ["labour", "unorganized worker", "pension", "financial"],
    target_gender: "All",
    target_occupations: ["Daily Wage Labourer", "Unorganized Worker", "Labourer"],
    min_age: 18,
    max_age: 40,
    income_limit: 15000, // Monthly, roughly 1.8L PA. Treating as PA for matching:
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: true,
    is_bpl_only: false
  },

  // =====================
  // PREGNANT WOMEN
  // =====================
  {
    id: "pmmvy",
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    category: "Pregnant Women",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "A maternity benefit program providing partial compensation for the wage loss.",
    benefits: "₹5,000 cash incentive in three installments for the first living child.",
    required_documents: ["Aadhaar Card", "MCP Card", "Bank passbook"],
    application_link: "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
    offline_process: null,
    nearest_office: "Anganwadi Centre / ASHA Worker",
    tags: ["women", "pregnant", "maternity", "health", "financial"],
    target_gender: "Female",
    target_occupations: ["All"],
    min_age: 18,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: true,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "janani-suraksha-yojana",
    name: "Janani Suraksha Yojana (JSY)",
    category: "Pregnant Women",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Safe motherhood intervention under the National Health Mission.",
    benefits: "Cash assistance for institutional delivery (varies by state/area).",
    required_documents: ["Aadhaar Card", "JSA Card / BPL Card", "Bank passbook"],
    application_link: null,
    offline_process: "Register with the local ASHA worker or at the nearest Primary Health Centre (PHC) during pregnancy.",
    nearest_office: "Primary Health Centre (PHC) or ASHA worker",
    tags: ["women", "pregnant", "health", "maternity", "financial"],
    target_gender: "Female",
    target_occupations: ["All"],
    min_age: 18,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: true,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: true
  },

  // =====================
  // SENIOR CITIZENS
  // =====================
  {
    id: "ignoaps",
    name: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    category: "Senior Citizens",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Non-contributory old age pension scheme for BPL individuals.",
    benefits: "₹200 to ₹500 per month (State governments often add their own contribution).",
    required_documents: ["Aadhaar Card", "BPL Card / Income Certificate", "Age Proof", "Bank Passbook"],
    application_link: "https://nsap.nic.in/",
    offline_process: "Submit the NSAP application form at the local Gram Panchayat or Municipal Office.",
    nearest_office: "Gram Panchayat / Municipal Office",
    tags: ["senior citizen", "pension", "financial", "bpl"],
    target_gender: "All",
    target_occupations: ["All"],
    min_age: 60,
    max_age: null,
    income_limit: null, // BPL acts as proxy
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: true,
    is_daily_wage_only: false,
    is_bpl_only: true
  },
  {
    id: "senior-citizens-savings-scheme",
    name: "Senior Citizens Savings Scheme (SCSS)",
    category: "Senior Citizens",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "A government-backed savings instrument offered to Indian residents aged over 60 years.",
    benefits: "High interest rate, regular income, and tax benefits.",
    required_documents: ["Aadhaar Card", "PAN Card", "Age Proof", "Photographs"],
    application_link: null,
    offline_process: "Open an SCSS account at any authorized Post Office or designated Bank branch.",
    nearest_office: "Post Office / Bank Branch",
    tags: ["senior citizen", "savings", "financial", "investment"],
    target_gender: "All",
    target_occupations: ["All"],
    min_age: 60,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: true,
    is_daily_wage_only: false,
    is_bpl_only: false
  },

  // =====================
  // EMPLOYMENT / SKILLS
  // =====================
  {
    id: "pm-kaushal-vikas-yojana",
    name: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
    category: "Employment",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Skill certification scheme to enable Indian youth to take up industry-relevant skill training.",
    benefits: "Free skill training, certification, and placement assistance.",
    required_documents: ["Aadhaar Card", "Bank Account Details", "Passport size photographs"],
    application_link: "https://www.pmkvyofficial.org/",
    offline_process: null,
    nearest_office: "PMKVY Training Centre",
    tags: ["employment", "skill", "training", "youth"],
    target_gender: "All",
    target_occupations: ["Unemployed", "Student", "Labourer", "All"],
    min_age: 15,
    max_age: 45,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: false
  },
  {
    id: "ayushman-bharat-pmjay",
    name: "Ayushman Bharat PM-JAY",
    category: "Healthcare",
    central_or_state: "Central",
    applicable_states: ["All"],
    description: "Health insurance scheme for poor, deprived rural families and identified occupational categories of urban workers' families.",
    benefits: "Health cover of ₹5 lakhs per family per year for secondary and tertiary care hospitalization.",
    required_documents: ["Aadhaar Card", "Ration Card"],
    application_link: "https://pmjay.gov.in/",
    offline_process: null,
    nearest_office: "Empanelled Hospital / CSC",
    tags: ["health", "insurance", "medical", "hospitalization", "bpl"],
    target_gender: "All",
    target_occupations: ["All"],
    min_age: null,
    max_age: null,
    income_limit: null,
    is_student_only: false,
    is_farmer_only: false,
    is_pregnant_only: false,
    is_senior_only: false,
    is_daily_wage_only: false,
    is_bpl_only: true
  }
];
